print("Welcome to the band name generator")
city = input("What is the name of your hometown? \n")
pet = input("what is the name of your pet? \n")
color = input("what is your favorite color? \n")
print("Your band name is: " + color + " " + pet + " " + city)